### ISSUE TITLE
Question about your es7 async/wait post

### ISSUE THREAD

**Issue by Sinewyk** [spion/spion.github.com#5]
These:

> ```javascript
//doesn't work
async function renderChapters(urls) {
  urls.map(getJSON).forEach(j => addToPage((await j).html));
}
// works
async function renderChapters(urls) {
  urls.map(getJSON).forEach(async j => addToPage((await j).html));
}
```

In the working example is there is a reason for the outer function to be marked as async ?
Couldn't it simply be 
```js
/* no async there */function renderChapters(urls) {
  urls.map(getJSON).forEach(async j => addToPage((await j).html));
}
```
unless I'm missing something ?

**Comment by spion** [comment]
Yeah it could because await isn't used.

**Comment by Sinewyk** [comment]
Thanks ^^.
